services:
  - type: web
    name: passbi-gtfs-v1
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/impactsolutionsas/passbi-gtfs-v1.git
    branch: main
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false  # Ã€ configurer manuellement dans le dashboard Render
      - key: GTFS_DATA_PATH
        value: ./data/gtfs

